### ISSUE TITLE
List of bookings results

### ISSUE THREAD

**Issue by FilipMessa** [kiwicom/margarita#26]
# List of Results

- [x] Style one way flight (#90)
- [x] Style return flights (#90)
- [x] Update price structure  (#90)
from:
    ```
    ResultsListItem on Itinerary {
      currency
      price
      localDeparture
      ...
    }
    ```
    to:
    ```
    ResultsListItem on Itinerary {
      price {
        value
        currency
      }
      localDeparture
      ...
    }
    ```
- [x] Create timeline image in `ConnectionCard` as RN elements, not as image 
- [x] Style loading (#90)
- [x] 8) Polish styling of `ConnectionCard` in Universal components. Date should be bold, use different fonts, dotted line, and use cards with different background. (#90)
- [x] handle not found/error states (#126)
- [x] Set proper `locale` (e.g `en-US`) according to mobile device to price settings (`ResultsListItem.js`). Probably using by `Expo.Util.getCurrentLocaleAsync` (https://docs.expo.io/versions/v25.0.0/sdk/util)
- [ ] ~~Use `Card` component~~ (we don't need it in othere component for now)
- [ ] ~~Get name of the airline in `ResultsListItem.js`.~~ (not important, we don't show it anywhere)
- [ ] ~~`TripSegmentProps` and `CarrierData` should be exportable from Universal components~~ ( not part of universal-components anymore)
- [ ] ~~Separate `getDateTimeInterval` and `intervalToString` to utils~~ (should be refactored in #123 )
- [ ] ~~Handle cases when we don't have some data from GraphQL/REST server (`getRouteItem` in `RestultsListItem.js`)~~ (part of #123 )

- [x] Show and style header title (OSL -> PRG) on the web (#90)

<img width="341" alt="screen shot 2018-12-11 at 07 08 37" src="https://user-images.githubusercontent.com/6354326/49781603-b0f74080-fd13-11e8-8aa9-432aba7610a4.png">
<img width="329" alt="screen shot 2018-12-11 at 07 08 28" src="https://user-images.githubusercontent.com/6354326/49781604-b0f74080-fd13-11e8-91fe-fb16af13f967.png">

**Comment by FilipMessa** [comment]
Wait until issue(create trip component) on universal will be done.https://github.com/kiwicom/universal-components/issues/92
